
services:
  - type: web
    name: earnzone-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_LINK
        sync: false
      - key: MOVIE_GROUP_ID
        sync: false
      - key: MOVIE_GROUP_LINK
        sync: false
