services:
  - type: web
    name: movie-earning-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:flask_app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "7315805581"
      - key: MONGO_URI
        sync: false
      - key: WEB_APP_URL
        value: https://promotion-user.onrender.com
      - key: PORT
        value: 10000
    autoDeploy: true
